on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
name: Deploy Extension
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Prepublish
        run: npm run vscode:prepublish
      - name: Publish to VS Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
# name: Release
# on:
#   push:
#     branches:
#       - master

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Automatic GitHub Release
#         uses: justincy/github-action-npm-release@2.0.1
#         id: release
#       - uses: actions/setup-node@v1
#         if: steps.release.outputs.released == 'true'
#         with:
#           registry-url: 'https://npm.pkg.github.com'
#       - name: Publish
#         if: steps.release.outputs.released == 'true'
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
