on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
name: Deploy Extension
jobs:
  CI:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Prepublish
        run: npm run vscode:prepublish
      - name: Publish to VS Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
