name: Lint
on:
  push:
    branches:
      - "*"
  # pull_request:
  #   branches:
  #     - master
branches:
  - development
  - staging
  - production

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs: # list of things to do
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@latest
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@latest

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
